# Generated by Django 5.0.4 on 2024-10-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_alter_city_lat_alter_city_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='city',
            name='lon',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
    ]
